NOAA_BASE_API = "https://www.ncdc.noaa.gov/cdo-web/api/v2"


NOAA_API_DATA_PATH = NOAA_BASE_API + "/data" 
# params:
# * datasetid: REQUIRED. Accepts a single valid dataset id. Data returned will be from the dataset specified.
# datatypeid: Optional. Accepts a valid data type id or a chain of data type ids separated by ampersands. Stations returned will contain all of the data type(s) specified
# locationid: Optional. Accepts a valid location id or a chain of location ids separated by ampersands. Stations returned will contain data for the location(s) specified
# stationid: Optional. Accepts a valid station id or a chain of of station ids separated by ampersands. Data returned will contain data for the station(s) specified.
# * startdate: REQUIRED. Accepts valid ISO formated date (YYYY-MM-DD) or date time (YYYY-MM-DDThh:mm:ss). Data returned will be after the specified date. Annual and Monthly data will be limited to a ten year range while all other data will be limted to a one year range.
# * enddate: REQUIRED. Accepts valid ISO formated date (YYYY-MM-DD) or date time (YYYY-MM-DDThh:mm:ss). Data returned will be before the specified date. Annual and Monthly data will be limited to a ten year range while all other data will be limted to a one year range.
# units: Optional. Accepts the literal strings 'standard' or 'metric'. Data will be scaled and converted to the specified units. If a unit is not provided then no scaling nor conversion will take place.
# sortfield: Optional. The field to sort results by. Supports id, name, mindate, maxdate, and datacoverage fields
# sortorder: Optional. Which order to sort by, asc or desc. Defaults to asc
# limit: Optional. Defaults to 25, limits the number of results in the response. Maximum is 1000
# offset: Optional. Defaults to 0, used to offset the resultlist. The example would begin with record 24
# includemetadata: Optional. Defaults to true, used to improve response time by preventing the calculation of result metadata.

NOAA_API_STATIONS_PATH = NOAA_BASE_API + "/stations" # optional /%s for stationid
# params:
# datasetid: Optional. Accepts a valid dataset id or a chain of dataset ids separated by ampersands. Stations returned will be supported by dataset(s) specified
# locationid: Optional. Accepts a valid location id or a chain of location ids separated by ampersands. Stations returned will contain data for the location(s) specified
# datacategoryid: Optional. Accepts a valid data category id or an array of data category ids. Stations returned will be associated with the data category(ies) specified
# datatypeid: Optional. Accepts a valid data type id or a chain of data type ids separated by ampersands. Stations returned will contain all of the data type(s) specified
# extent: Optional. The desired geographical extent for search. Designed to take a parameter generated by Google Maps API V3 LatLngBounds.toUrlValue. Stations returned must be located within the extent specified.
# startdate: Optional. Accepts valid ISO formated date (yyyy-mm-dd). Stations returned will have data after the specified date. Paramater can be use independently of enddate
# enddate: Optional. Accepts valid ISO formated date (yyyy-mm-dd). Stations returned will have data before the specified date. Paramater can be use independently of startdate
# sortfield: Optional. The field to sort results by. Supports id, name, mindate, maxdate, and datacoverage fields
# sortorder: Optional. Which order to sort by, asc or desc. Defaults to asc
# limit: Optional. Defaults to 25, limits the number of results in the response. Maximum is 1000
# offset: Optional. Defaults to 0, used to offset the resultlist. The example would begin with record 24

NOAA_FETCH_STATIONS_BY_LAT_LONG = NOAA_API_STATIONS_PATH + "?extent=%.4f,%.4f,%.4f,%.4f"
# expects 4 parameters min_lat, min_long, max_lat, max_long
# from 1 lat,long : min_lat=lat-0.05,min_long=lat-0.05,max_lat=lat+0.05, max_long=long+0.05

# IMPORTANT DATASETS
#           "uid": "gov.noaa.ncdc:C00861",
# 			"mindate": "1763-01-01",
# 			"maxdate": "2026-03-19",
# 			"name": "Daily Summaries",
# 			"datacoverage": 1,
#			"id": "GHCND"
#
#			"uid": "gov.noaa.ncdc:C00823",
#			"mindate": "2010-01-01",
#			"maxdate": "2010-12-31",
#			"name": "Normals Daily",
#			"datacoverage": 1,
#			"id": "NORMAL_DLY"
#
#			"uid": "gov.noaa.ncdc:C00824",
#			"mindate": "2010-01-01",
#			"maxdate": "2010-12-31",
#			"name": "Normals Hourly",
#			"datacoverage": 1,
#			"id": "NORMAL_HLY"

NOAA_LOCATIONS_PATH = NOAA_BASE_API + "/locations"
# params:
# datasetid: Optional. Accepts a valid dataset id or a chain of dataset ids separated by ampersands. Locations returned will be supported by dataset(s) specified.
# locationcategoryid: Optional. Accepts a valid location id or a chain of location category ids separated by ampersands. Locations returned will be in the location category(ies) specified.
# datacategoryid: Optional. Accepts a valid data category id or an array of data category IDs. Locations returned will be associated with the data category(ies) specified.
# startdate: Optional. Accepts valid ISO formated date (yyyy-mm-dd). Locations returned will have data after the specified date. Paramater can be use independently of enddate.
# enddate: Optional. Accepts valid ISO formated date (yyyy-mm-dd). Locations returned will have data before the specified date. Paramater can be use independently of startdate.
# sortfield: Optional. The field to sort results by. Supports id, name, mindate, maxdate, and datacoverage fields.
# sortorder: Optional. Which order to sort by, asc or desc. Defaults to asc.
# limit: Optional. Defaults to 25, limits the number of results in the response. Maximum is 1000.
# offset: Optional. Defaults to 0, used to offset the resultlist. The example would begin with record 24.

# direct path to get all US location ids for each state
NOAA_UNITED_STATES_LOCATIONS = NOAA_LOCATIONS_PATH + "?locationcategoryid=ST&limit=52"


NOAA_FETCH_LOCATIONS_BY_STATE = NOAA_LOCATIONS_PATH + "?locationid=%s"
# expects locationid (State)

NOAA_FETCH_ACTIVE_LOCATIONS_BY_STATE = NOAA_FETCH_LOCATIONS_BY_STATE + "&start_date=%s"
# expects data in format (yyyy-mm-dd) for when station must have data after