# Generated by Django 6.0.3 on 2026-03-30 00:34

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('base_temp', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('abbr', models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geolocation', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('farm', models.ForeignKey(db_column='farmid', on_delete=django.db.models.deletion.CASCADE, to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='LifeStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('gdd_C', models.IntegerField(blank=True, null=True)),
                ('gdd_F', models.IntegerField(blank=True, null=True)),
                ('stage', models.FloatField()),
                ('crop', models.ForeignKey(db_column='cropid', on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='PlantedCrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop', models.ForeignKey(db_column='cropid', on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('field', models.ForeignKey(db_column='fieldid', on_delete=django.db.models.deletion.CASCADE, to='api.field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='crop',
            field=models.ManyToManyField(through='api.PlantedCrop', to='api.crop'),
        ),
        migrations.AddField(
            model_name='crop',
            name='state',
            field=models.ManyToManyField(to='api.state'),
        ),
        migrations.CreateModel(
            name='GDD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('calc_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('sine', 'Sine'), ('other', 'Other'), ('baskerville-emin', 'Baskerville Emin')], null=True, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('gdd', models.FloatField()),
                ('plantedcrop', models.ForeignKey(db_column='plantedcropid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='gdds', to='api.plantedcrop')),
            ],
            options={
                'unique_together': {('plantedcrop', 'day', 'calc_type')},
            },
        ),
    ]
